name = "magiclamp/governance"
version = "0.0.1"
compiler = "v1.1.21"
plutus = "v3"
license = "Apache-2.0"
description = ""

[[dependencies]]
name = "aiken-lang/stdlib"
version = "7d5cee54b2bb4eea211ae3bd806c7c39e5fd899d"
source = "github"

[[dependencies]]
name = "aiken-lang/merkle-patricia-forestry"
version = "2.1.0"
source = "github"

[config]
